name: Check labels
run-name: "ddddd"
on:
   pull_request_target:
      branches:
         - "master"
         - "[0-9]+.[0-9]+.z"
         - "[0-9]+.[0-9]+.[0-9]"
         - "[0-9]+.[0-9]+.[0-9]+-BETA-[0-9]+"
         - "[0-9]+.[0-9]+.[0-9]+-DEVEL-[0-9]+"
         - "data-migration-5.3"
      types:
         - opened
         - synchronize
         - reopened
         - labeled
         - unlabeled
jobs:
  check_labels:
    name: Check for mandatory labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
      - name: Test App
        run: |
          curl -X PATCH  -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{ secret.GITHUB_TOKEN }}" "https://api.github.com/repos/nishaatr/hellogitworld/check-runs/21218694827" -d '{"output":{"title":"Mighty Readme report","summary":"SUMMARY","text":"TEXT"}}' 
      - name: Test labels for 'Source:'
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          prefix_mode: true
          one_of: "Source:"
          repo_token: ${{ secrets.GH_TOKEN }}
      - name: Test labels for 'Team:'
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          prefix_mode: true
          one_of: "Team:"
          repo_token: ${{ secrets.GH_TOKEN }}

