name: Report Metrics

on: [workflow_dispatch]

jobs:
  report:
    name: Slack
    runs-on: ubuntu-latest

    steps:
      - uses: Addepar/github-metrics@v1.2.0
        with:
          github-owner: nishaatr
          github-repo: angular5-quickstart
          github-token: ${{secrets.GITHUB_TOKEN}}
          slack-app-token: xoxb-2159467153-5408539429777-ZOg3wPvWRN6maYP0ZlQGXTzU
          slack-channel-id: D057B611ABY
          post-to-slack: "false"
          log-debug-messages: "true"
