name: Report Metrics

on: [workflow_dispatch]

jobs:
  report:
    name: Slack
    runs-on: ubuntu-latest

    steps:
      - uses: Addepar/github-metrics@v1.2.0
        with:
          github-owner: nishaatr
          github-repo: angular5-quickstart
          github-token: ${{secrets.GITHUB_TOKEN}}
          slack-app-token: xoxe.xoxp-1-Mi0yLTIxNTk0NjcxNTMtNTI2ODQ1MDA1Nzg4OS01Mzk4MDM4NzcxNzE2LTUzOTI2NjYyNzEwNjEtOTBjMWFkYzk1ZDZjZGJjYzBjOTEzMWJjNTY1MGRjY2EwYzUxNzMwZTIyMDcxNGU2YjYwNzJjNmZjYjY4ZGZkNg
          slack-channel-id: D057B611ABY
          post-to-slack: "false"
          log-debug-messages: "true"
